---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
## Basic Setting
```{r setoptions,echo=FALSE}
#opts_chunk$set(echo=TRUE)
require(ggplot2)
library(scales)
library(lattice)
```
## Loading and preprocessing the data

```{r}
setInternet2(use = TRUE)
temp_file <- tempfile()
dataURL <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
download.file(dataURL, temp_file)
unzip(temp_file,"activity.csv")
#setwd("E:/DataScience/Reproducible Research Project 1/")
data <- read.csv("activity.csv", header=T)
data_narm <- na.omit(data)
head(data_narm)
```
## What is mean total number of steps taken per day?
```{r}
Total_by_date <- aggregate(data_narm$steps, list(Date = data_narm$date), 
                           FUN="sum")
```

```{r}
ggplot(data_narm, aes(date,steps)) + geom_bar(stat = "identity", 
colour = "steelblue", fill = "steelblue", width = 0.7) + 
facet_grid(. ~ date, scales = "free") + 
labs(title = "Histogram of Total Number of Steps Taken Each Day without NA", 
x = "Date", y = "Total number of steps")
```

```{r}
mean(Total_by_date$x)
median(Total_by_date$x)
```
## What is the average daily activity pattern?
```{r}
Daily_ave <- aggregate(data_narm$steps, list(interval = data_narm$interval), 
                      FUN="mean")
```

```{r}
ggplot(Daily_ave, aes(interval,x)) + 
geom_line(colour = "steelblue", width = 0.7) + 
labs(title = "Daily Average Activity Pattern", 
x = " Daily 5-minute interval (x-axis)", y = "Average number of steps")
```

```{r}
maxavginterval = Daily_ave$interval[Daily_ave$x == max(Daily_ave$x)]
print(sprintf("Daily 5-min time Interval with maximum average steps taken : %i "
, maxavginterval))
```
## Imputing missing values

```{r}
t_row <- nrow(data)
t_row_narm <- nrow(data_narm)
t_row_na <- t_row-t_row_narm
print(sprintf("We have %i rows of NA data", t_row_na))
```

```{r}
data_to_fill <- data
names(Daily_ave)[2] <- "ave_steps"

for(i in 1:t_row){
  if(is.na(data_to_fill$steps[i])){
    data_to_fill$steps[i] <- Daily_ave[which(data_to_fill$interval[i]==
                                               Daily_ave$interval),]$ave_steps
  }
}

head(data_to_fill)
```

```{r}
ggplot(data_to_fill, aes(date,steps)) + geom_bar(stat = "identity", 
colour = "steelblue", fill = "steelblue", width = 0.7) + 
facet_grid(. ~ date, scales = "free") + 
labs(title = "Histogram of Total Number of Steps Taken Each Day with All Data", 
x = "Date", y = "Total number of steps")
```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
new <- data_to_fill
new$date <- as.Date(new$date, "%Y-%m-%d")
new$weekdays <- "weekday"
new$weekdays[weekdays(new$date) %in% c("Saturday")] <- "weekend"
new$weekdays[weekdays(new$date) %in% c("Sunday")] <- "weekend"
new$week <- as.factor(new$weekdays)
```
```{r}
new_ave <- aggregate(new$steps, list(interval = as.numeric(new$interval),
            weekdays=new$weekdays), FUN="mean")

names(new_ave)[3] <- "ave_step"
head(new_ave)
```

```{r}
ggplot(new_ave[1:nrow(new_ave)/2,], aes(interval,ave_step)) + 
geom_line(colour = "steelblue", width = 0.7) + 
labs(title = "Daily Average Activity Pattern (Weekdays)", 
x = " Daily 5-minute interval (x-axis)", y = "Average number of steps")
```

```{r}
ggplot(new_ave[(nrow(new_ave)/2+1):nrow(new_ave),], aes(interval,ave_step)) + 
geom_line(colour = "steelblue", width = 0.7) + 
labs(title = "Daily Average Activity Pattern (weekends)", 
x = " Daily 5-minute interval (x-axis)", y = "Average number of steps")
```